#!/bin/bash

# =============================================================================
# Healthcore stop script
# =============================================================================
# Stops all microservices (bridges, broker, server, healthcheck) via PM2.
#
# Supported platforms:
#   - macOS / Linux: runs natively in bash
#   - Windows: requires Git Bash (OSTYPE=msys) or Cygwin (OSTYPE=cygwin)
#
# Usage:
#   chmod +x production-stop.sh
#   ./production-stop.sh
# =============================================================================

# Exit immediately if any command fails
set -e

# Ensure locally installed npm binaries are available in PATH
export PATH="./node_modules/.bin:$PATH"

# --- Step 1: Check PM2 -----------------------------------------------------
echo "🔧 Checking PM2 installation ..."
if ! command -v pm2 > /dev/null 2>&1; then
  echo "PM2 is not installed. Nothing to stop."
  exit 0
fi

# --- Step 2: Remove Autostart (macOS / Linux only) -------------------------
# Removes the system init script that was generated by "pm2 startup".
# Not needed on Windows — handled by pm2-windows-startup.
if [[ "$OSTYPE" != "msys" && "$OSTYPE" != "cygwin" ]]; then
  echo "🔄 Removing autostart ..."
  pm2 unstartup || true
fi

# --- Step 3: Stop and Delete All Services ----------------------------------
# Stop all running PM2 processes and remove them from the process list.
echo "🛑 Stopping all PM2 processes ..."
pm2 stop all || true

echo "🗑️  Deleting all PM2 processes ..."
pm2 delete all || true

# --- Step 4: Kill PM2 Daemon -----------------------------------------------
# Fully shuts down the PM2 daemon process.
echo "💀 Killing PM2 daemon ..."
pm2 kill || true

echo "✅ All services stopped successfully!"
